"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//-- Importar clase
var easyCalc_1 = require("./easyCalc");
//-- Pruebas
new easyCalc_1.EasyCalc();
console.log("`----------INICIO----------");
console.log(easyCalc_1.EasyCalc.getResultado());
console.log(easyCalc_1.EasyCalc.getHistorial());
console.log(easyCalc_1.EasyCalc.getFormatos());
console.log("`--------------------------");
console.log("`----------SUMA----------");
easyCalc_1.EasyCalc.suma([2, 3, 5]);
console.log(easyCalc_1.EasyCalc.getResultado());
console.log(easyCalc_1.EasyCalc.getHistorial());
console.log(easyCalc_1.EasyCalc.getFormatos());
console.log("`--------------------------");
console.log("`----------RESTA----------");
easyCalc_1.EasyCalc.resta([10, 2, 3]);
console.log(easyCalc_1.EasyCalc.getResultado());
console.log(easyCalc_1.EasyCalc.getHistorial());
console.log(easyCalc_1.EasyCalc.getFormatos());
console.log("`--------------------------");
console.log("`------MULTIPLICACION------");
easyCalc_1.EasyCalc.multiplicacion([2, 2, 2]);
console.log(easyCalc_1.EasyCalc.getResultado());
console.log(easyCalc_1.EasyCalc.getHistorial());
console.log(easyCalc_1.EasyCalc.getFormatos());
console.log("`--------------------------");
console.log("`--------DIVISION----------");
easyCalc_1.EasyCalc.division([10, 2]);
console.log(easyCalc_1.EasyCalc.getResultado());
console.log(easyCalc_1.EasyCalc.getHistorial());
console.log(easyCalc_1.EasyCalc.getFormatos());
console.log("`--------------------------");
console.log("`--------RESETEAR----------");
easyCalc_1.EasyCalc.resetear();
console.log(easyCalc_1.EasyCalc.getResultado());
console.log(easyCalc_1.EasyCalc.getHistorial());
console.log(easyCalc_1.EasyCalc.getFormatos());
console.log("`--------------------------");
